name: "kyma-project.io/create/mymodule" # required, the name of the Module
version: "0.0.1" # required, the version of the Module
manifest: "manifest.yaml" # required, relative path or remote URL to the manifests
# mandatory: false # optional, default=false, indicates whether the module is mandatory to be installed on all clusters
# defaultCR: "" # optional, relative path or remote URL to a YAML file containing the default CR for the module
# namespace: "" # optional, default=kcp-system, the namespace where the ModuleTemplate will be deployed
# security: "" # optional, name of the security scanners config file
# internal: false # optional, default=false, determines whether the ModuleTemplate should have the internal flag or not
# beta: false # optional, default=false, determines whether the ModuleTemplate should have the beta flag or not
# labels: map[] # optional, additional labels for the ModuleTemplate
# annotations: map[] # optional, additional annotations for the ModuleTemplate
# manager: "" # optional, the module resource that can be used to indicate the installation readiness of the module. This is typically the manager deployment of the module.