module-name: modulectl
kind: kcp
checkmarxOne:
  checkmarx_preset: golang
whitesource:
  language: golang-mod
  exclude:
    - "**/test/**"
    - "**/*_test.go"
    - "**/mocks/**"
  subprojects: false
