module-name: modulectl
kind: kcp
checkmarx-one:
  preset: go-default
  exclude:
    - "**/test/**"
    - "**/*_test.go"
    - "**/mocks/**"
mend:
  language: golang-mod
  exclude:
    - "**/test/**"
    - "**/*_test.go"
    - "**/mocks/**"
