name: Build modulectl1
on:
  pull_request:
    branches:
      - main
      - 'release-**'
  workflow_dispatch:
jobs:
  build2:
    name: Build modulectl3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Go setup
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'
      - name: "Run 'make build'"
        run: make build
