name: Build
on:
  pull_request:
    branches:
      - main
    workflow_call:
      inputs:
        version:
          description: 'Version used for release builds'
          required: false
          type: string
          default: ""
  workflow_dispatch:
jobs:
  build-modulectl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Go setup
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'
      - name: "Run 'make build'"
        run: |
          if [[ "${{ inputs.version }}" != "" ]]; then
            make build VERSION=${{ inputs.version }}
          else
            make build
          fi
