name: E2E Test - Create Scaffold

on:
  push:
    branches:
      - main
      - 'release-**'
  pull_request:
    branches:
      - main
      - 'release-**'
    paths:
      - 'go.mod'
      - 'go.sum'
      - '**.go'
jobs:
  e2e-test:
    name: E2E Test - Create Scaffold
    runs-on: ubuntu-latest
    steps:
      - name: Checkout modulectl
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'
      - name: Build modulectl
        run: |
          make build-linux
          chmod +x ./bin/modulectl-linux
          ls -la ./bin
          mv ./bin/modulectl-linux /usr/local/bin/modulectl
        timeout-minutes: 10
      - name: Run E2E Test - Create Scaffold
        run: |
          make -C tests/e2e test-create-scaffold
        timeout-minutes: 3
