name: "E2E test - modulectl scaffold"
on:
  pull_request:
    branches:
      - main
      - 'release-**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Go setup
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: 'go.sum'
      - name: Build
        run: |
          make build-linux
          chmod +x ./bin/modulectl-linux
          ls -la ./bin
          mv ./bin/modulectl-linux /usr/local/bin/modulectl
        timeout-minutes: 5
      - name: Run tests
        run: |
          make -C tests/e2e test-module-scaffold
        timeout-minutes: 3
